### ISSUE TITLE
Week 6 - roadmap, FN, docker, validator, metrics

### ISSUE THREAD

**Issue by pariweshsubedi** [pariweshsubedi/libra-kubernetes-document-verification#3]
- [x] Initial System Design
- [x] Check libra roadmap for upcoming changes
  - https://developers.libra.org/blog/2019/12/17/libra-core-roadmap-2
  - libra project board : https://github.com/orgs/libra/projects/1#card-28078342
- [x] Check multisig implementation

Questions : 
- What happens if the deployed script has to be changed in the future because of the vulnerability ? (invites hard fork)
- Think privacy of the data owner (student)
- How can students share proof of certification to companies and company only access the particular certificate proof?
